storage:
  minio:
    bucket_name: ${S3_BUCKET_NAME}
    paths:
      raw_zone: "raw/{file_group}/{provider}/{safe_filename}"
      processed_zone: "processed/{doc_id}"
    file_groups:
      documents:
        - ".pdf"
        - ".doc"
        - ".docx"
      images:
        - ".png"
        - ".jpg"
        - ".jpeg"
      texts:
        - ".txt"
        - ".csv"
      others:
        - "*"